import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AppNav from "@/components/navigation/app-nav";
import Footer from "@/components/navigation/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <AppNav />
          <section>{children}</section>
          <Toaster position="top-center" richColors closeButton />
        </div>
        <Footer />
        <div className="fixed bottom-8 right-8 z-40">
          <button
            aria-label="Chat with AI Agent"
            className="flex items-center justify-center gap-2 h-14 px-6 bg-[#add1ea] text-[#121517] rounded-full shadow-xl hover:bg-[#9cbcd3] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-[#121517] focus:ring-[#add1ea] transition-all duration-300 group"
          >
            <svg
              className="h-6 w-6 transform group-hover:rotate-12 transition-transform"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.5"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M8.625 12a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375M21 12c0 4.556-3.862 8.25-8.625 8.25S3.75 16.556 3.75 12 7.612 3.75 12.375 3.75 21 7.444 21 12z"
                strokeLinecap="round"
                strokeLinejoin="round"
              ></path>
            </svg>
            <span className="text-base font-bold tracking-wide">AI Agent</span>
          </button>
        </div>
      </body>
    </html>
  );
}
